### ISSUE TITLE
请问这个插件可以用在Hoshinobot的nonebot2版本嘛？

### ISSUE THREAD

**Issue by 0769559** [pcrbot/ai_setu#11]
https://github.com/shewinder/shebot_nb2
用的这个机器人，想赶时髦加个ai功能 结果折腾下来没弄成才想起我的这是个nonebot2。。。
![image](https://user-images.githubusercontent.com/22361624/203761385-b5ef1ffd-ec1f-4b8e-820a-8f0213b73257.png)

**Comment by sanshanya** [comment]
没有用到nonebot1的原装触发器,所以大概率是能用于hoshinobot的nb2版本

**Comment by 0769559** [comment]
> 没有用到nonebot1的原装触发器,所以大概率是能用于hoshinobot的nb2版本

以按照你写的使用教程一步一步下来，config.yaml里面全默认没有动。好像插件没能成功运行。我查了下原版hoshinobot添加插件后开启的方法是hoshino\config\_bot_.py里添加，但是我nb2里没有这个文件夹了，是在nb2里的根目录.env添加吗？另外出现了下面的报错



root@racknerd-ce2ee0:~/shebot_nb2# python3 run.py
11-24 23:42:52 [SUCCESS] nonebot | NoneBot is initializing...
11-24 23:42:53 [INFO] nonebot | Current Env: prod
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "ls"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "schedule_manage"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "listenmeta"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "echo"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "interact_handle"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "help"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "black"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "test"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "zai"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "service_manage"
11-24 23:42:53 [ERROR] nonebot | Failed to import "saujo"
Traceback (most recent call last):
  File "/root/shebot_nb2/run.py", line 39, in <module>
    nonebot.load_plugins(module)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 1005, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "hoshino/modules/ai_setu/saujo.py", line 2, in <module>
    from hoshino import Service, priv
ImportError: cannot import name 'priv' from 'hoshino' (/root/shebot_nb2/hoshino/__init__.py)
11-24 23:42:53 [ERROR] nonebot | Failed to import "until"
Traceback (most recent call last):
  File "/root/shebot_nb2/run.py", line 39, in <module>
    nonebot.load_plugins(module)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 1005, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "hoshino/modules/ai_setu/until.py", line 5, in <module>
    from hoshino import aiorequests
ImportError: cannot import name 'aiorequests' from 'hoshino' (/root/shebot_nb2/hoshino/__init__.py)
11-24 23:42:53 [ERROR] nonebot | Failed to import "translate"
Traceback (most recent call last):
  File "/root/shebot_nb2/run.py", line 39, in <module>
    nonebot.load_plugins(module)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 1005, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "hoshino/modules/ai_setu/translate.py", line 1, in <module>
    from hoshino import aiorequests
ImportError: cannot import name 'aiorequests' from 'hoshino' (/root/shebot_nb2/hoshino/__init__.py)
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "db"
11-24 23:42:53 [ERROR] nonebot | Failed to import "easygradio"
Traceback (most recent call last):
  File "/root/shebot_nb2/run.py", line 39, in <module>
    nonebot.load_plugins(module)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 1005, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "hoshino/modules/ai_setu/easygradio.py", line 1, in <module>
    from hoshino import aiorequests
ImportError: cannot import name 'aiorequests' from 'hoshino' (/root/shebot_nb2/hoshino/__init__.py)
/usr/local/lib/python3.9/dist-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "setusearch"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "setuadd"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "setu"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "sync_tag"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "broadcast"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "greet"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "anti_msg_recall"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "antiflash"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "pixivrank"
11-24 23:42:53 [SUCCESS] nonebot | Succeeded to import "pidhelper"
11-24 23:42:53 [SUCCESS] nonebot | Running NoneBot...
11-24 23:42:53 [INFO] uvicorn | Started server process [26294]
