### ISSUE TITLE
这个报错是什么原因呢

### ISSUE THREAD

**Issue by liuzj288** [pcrbot/ai_setu#13]
[2022-11-27 21:38:56,616 nonebot] ERROR: Failed to import and load "hoshino.modules.ai_setu.db", error: module 'PIL.Image' has no attribute 'Resampling'
[2022-11-27 21:38:56,632 nonebot] ERROR: module 'PIL.Image' has no attribute 'Resampling'
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\__init__.py", line 4, in <module>
    from . import db,until
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\until.py", line 67, in <module>
    help.救命啊() #初始化帮助
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\help.py", line 172, in 救命啊
    draw_it(contentlist,f"{curpath}/help_main")
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\help.py", line 148, in draw_it
    im = im.resize((30+maxwidth+30, maxheight+100),Image.Resampling.LANCZOS)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
[2022-11-27 21:38:57,293 nonebot] INFO: Succeeded to import and load "hoshino.modules.ai_setu.easygradio"
[2022-11-27 21:38:57,293 nonebot] INFO: Succeeded to import and load "hoshino.modules.ai_setu.help"
[2022-11-27 21:38:57,569 nonebot] ERROR: Failed to import and load "hoshino.modules.ai_setu.saujo", error: module 'PIL.Image' has no attribute 'Resampling'
[2022-11-27 21:38:57,569 nonebot] ERROR: module 'PIL.Image' has no attribute 'Resampling'
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\__init__.py", line 4, in <module>
    from . import db,until
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\until.py", line 67, in <module>
    help.救命啊() #初始化帮助
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\help.py", line 172, in 救命啊
    draw_it(contentlist,f"{curpath}/help_main")
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\help.py", line 148, in draw_it
    im = im.resize((30+maxwidth+30, maxheight+100),Image.Resampling.LANCZOS)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
[2022-11-27 21:38:57,569 nonebot] INFO: Succeeded to import and load "hoshino.modules.ai_setu.translate"
[2022-11-27 21:38:57,850 nonebot] ERROR: Failed to import and load "hoshino.modules.ai_setu.until", error: module 'PIL.Image' has no attribute 'Resampling'
[2022-11-27 21:38:57,850 nonebot] ERROR: module 'PIL.Image' has no attribute 'Resampling'
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\__init__.py", line 4, in <module>
    from . import db,until
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\until.py", line 67, in <module>
    help.救命啊() #初始化帮助
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\help.py", line 172, in 救命啊
    draw_it(contentlist,f"{curpath}/help_main")
  File "C:\Users\Alex\Documents\HoshinoBot\hoshino\modules\ai_setu\help.py", line 148, in draw_it
    im = im.resize((30+maxwidth+30, maxheight+100),Image.Resampling.LANCZOS)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'

**Comment by sanshanya** [comment]
Pillow版本过低

**Comment by liuzj288** [comment]
> Pillow版本过低
路路的api这样设置有啥问题吗？目前就sd绘图能正常用
![image](https://user-images.githubusercontent.com/13833404/204141099-a1beb0e0-38f8-49e7-bfc4-c959fe720d50.png)

**Comment by sanshanya** [comment]
路路跑路了
