### ISSUE TITLE
本地的sd模型，在调用的时候出现这个问题是什么原因

### ISSUE THREAD

**Issue by dajiaofirst** [pcrbot/ai_setu#14]
[2022-11-28 15:38:50,936 nonebot] INFO: Self: 2078087474, Message 1015289228 from 1832629718@[群:131136330]: 'SD绘图 miku'
[2022-11-28 15:38:50,938 绘图] INFO: Message 1015289228 triggered text2img_sd.
[2022-11-28 15:38:51,238 绘图] ERROR: <class 'KeyError'> occured when text2img_sd handling message 1015289228.
[2022-11-28 15:38:51,238 绘图] ERROR: 'images'
Traceback (most recent call last):
  File "/home/caixukun/HoshinoBot/hoshino/msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "/home/caixukun/HoshinoBot/hoshino/modules/ai_setu/__init__.py", line 62, in text2img_sd
    result_msg,error_msg = await until.get_imgdata_sd(tag_dict,way=0)
  File "/home/caixukun/HoshinoBot/hoshino/modules/ai_setu/until.py", line 395, in get_imgdata_sd
    imgdata = imgdata["images"][0]
KeyError: 'images'

**Comment by dajiaofirst** [comment]
已经确认过本地是能够使用的，api填写的“Running on local URL:  http://*.*.*.*:7860”里面的url

**Comment by sanshanya** [comment]
超时了
检查sd webui的启动参数是否有--api

**Comment by dajiaofirst** [comment]
好的，谢谢，不过我添加了--api的参数

**Comment by sanshanya** [comment]
超时的原因可能有很多,请访问ip:7860/docs 调试&nbsp;
------------------

sansme
***@***.***



&nbsp;




------------------&nbsp;Original message&nbsp;------------------
From: "Agnes Digital"; 
Sendtime: Tuesday, Nov 29, 2022 9:58 AM
To: "pcrbot/ai_setu"; 
Cc: "sansme"; "State change"; 
Subject: Re: [pcrbot/ai_setu] 本地的sd模型，在调用的时候出现这个问题是什么原因 (Issue #14)





 
好的，谢谢，不过我添加了--api的参数

**Comment by dajiaofirst** [comment]
好的，谢谢了
