### ISSUE TITLE
关于启动时报error: module 'PIL.Image' has no attribute 'Resampling'错误的问题

### ISSUE THREAD

**Issue by EAloo** [pcrbot/ai_setu#22]
您好，我在部署您的插件时，遇到如下的问题
已经确认依赖没有问题，我的系统是Windows2012 R2 
[2023-01-06 15:21:40,584 nonebot] ERROR: Failed to import and load "hoshino.modules.ai_setu.db", error: module 'PIL.Image' has no attribute 'Resampling'
[2023-01-06 15:21:40,587 nonebot] ERROR: module 'PIL.Image' has no attribute 'Resampling'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\__init__.py", line 4, in <module>
    from . import db,until
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\until.py", line 67, in <module>
    help.救命啊() #初始化帮助
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\help.py", line 172, in 救命啊
    draw_it(contentlist,f"{curpath}/help_main")
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\help.py", line 148, in draw_it
    im = im.resize((30+maxwidth+30, maxheight+100),Image.Resampling.LANCZOS)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PIL\Image.py", line 77, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
[2023-01-06 15:21:40,792 nonebot] ERROR: Failed to import and load "hoshino.modules.ai_setu.saujo", error: module 'PIL.Image' has no attribute 'Resampling'
[2023-01-06 15:21:40,792 nonebot] ERROR: module 'PIL.Image' has no attribute 'Resampling'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\__init__.py", line 4, in <module>
    from . import db,until
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\until.py", line 67, in <module>
    help.救命啊() #初始化帮助
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\help.py", line 172, in 救命啊
    draw_it(contentlist,f"{curpath}/help_main")
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\help.py", line 148, in draw_it
    im = im.resize((30+maxwidth+30, maxheight+100),Image.Resampling.LANCZOS)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PIL\Image.py", line 77, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
[2023-01-06 15:21:40,952 nonebot] ERROR: Failed to import and load "hoshino.modules.ai_setu.until", error: module 'PIL.Image' has no attribute 'Resampling'
[2023-01-06 15:21:40,954 nonebot] ERROR: module 'PIL.Image' has no attribute 'Resampling'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\__init__.py", line 4, in <module>
    from . import db,until
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\until.py", line 67, in <module>
    help.救命啊() #初始化帮助
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\help.py", line 172, in 救命啊
    draw_it(contentlist,f"{curpath}/help_main")
  File "C:\bunaibot\HoshinoBot-master\HoshinoBot\hoshino\modules\ai_setu\help.py", line 148, in draw_it
    im = im.resize((30+maxwidth+30, maxheight+100),Image.Resampling.LANCZOS)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PIL\Image.py", line 77, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
希望得到您的帮助，如果需要其他的信息我也会尽力提供

**Comment by EAloo** [comment]
根据群友的帮助，确认是依赖版本问题，已经处理好了 。非常抱歉打扰您
